SUBROUTINE CALWQC(ISTL_,IS2TL_)  

  ! CHANGE RECORD  
  ! **  SUBROUTINE CALWQC CALCULATES THE CONCENTRATION OF DISSOLVED AND  
  ! **  SUSPENDED WATER QUALITY CONSTITUTENTS AT TIME LEVEL (N+1).  
  ! **  CALLED ONLY ON ODD THREE TIME LEVEL STEPS  
  ! **  DS-INTL: 2010-12  ADDED OMP, CLEANED UP CODE AND CONVERTED TO F90
  ! 2014-08           D H CHUNG        SET EXPLICIT PRECISIONS OF INTEGER & REAL

  USE GLOBAL  
  USE OMP_LIB
  
  IMPLICIT NONE
  
  INTEGER :: ISTL_,IS2TL_
  INTEGER :: L,K,IP,ITHD,NW,ND,LF,LL,LP
  
  INTEGER, SAVE             :: NACTIVEWQ
  INTEGER, SAVE,ALLOCATABLE :: IACTIVEWQ(:)
  
  REAL(RKD)   :: DSTIME
  REAL(RKD)   :: RCDZKK, RCDZKMK, CCLBTMP, CCUBTMP, CCMBTMP, EEB
  REAL(RKD)   :: TTDS         ! MODEL TIMING TEMPORARY VARIABLE
  
  ! If-EndIf counts the number of active WQ variables 
  ! and create IACTIVEWQ(NACTIVEWQ) to store the index of active WQ variable.
  IF( .NOT. ALLOCATED(IACTIVEWQ) )THEN
    ALLOCATE( IACTIVEWQ(NWQV) )
    IACTIVEWQ = 0
    NACTIVEWQ = 0
    
    DO NW = 1,NWQV
      IF( ISTRWQ(NW) == 1 )THEN
        NACTIVEWQ = NACTIVEWQ+1
        IACTIVEWQ(NACTIVEWQ) = NW
      ENDIF
    ENDDO
  ENDIF
  
  DELT=DT ! only use DT for 1D  and not need IS2TIM
  ! IS2TIM:  0 FOR USING 3 TIME LEVELS,
  ! 1 FOR 2 TIME LEVEL, EXPLICIT MOMENTUM SOLUTION
  ! 2 FOR 2 TIME LEVEL, IMPLICIT MOMENTUM SOLUTION
!   IF( IS2TIM >= 1 )THEN  
!     DELT=DT  
!   ENDIF  
  ITHD=1
  
  ! **  UPDATED TIME SERIES CONCENTRATION BOUNDARY CONDITIONS  
  ! **  3D ADVECTI0N TRANSPORT CALCULATION  
  TTDS=DSTIME(0)
  DO ND=1,NACTIVEWQ  
    NW=IACTIVEWQ(ND)
    CALL CALTRAN(ISTL_,IS2TL_,8,NW,WQV(1,1,NW),WQV(1,1,NW),ITHD)
    
    ! Qian: delete code for including ICE
    
  ENDDO  
  
  TWQADV=TWQADV+(DSTIME(0)-TTDS)  

  RETURN  
  
  END  

