SUBROUTINE WQWET

  ! *** RWQATM
  ! ** COMPUTES WET ATMOSPHERIC DEPOSITION USING CONSTANT CONCENTRATIONS
  ! ** FOR THE 22 STATE VARIABLES MULTIPLIED BY THE RAINFALL FLOW RATE      !VB CHANGED 21 TO 22
  ! ** ENTERING EACH GRID CELL.  COMPUTED LOADS ARE IN G/DAY.

  ! CHANGE RECORD

  USE GLOBAL
  IMPLICIT NONE

  INTEGER :: L,NW
  REAL    :: CV2,TIME

  !  CV2 = CONVERSION TO GET UNITS OF G/DAY
  !  WQATM(NW) HAS UNITS OF MG/L
  !  RAINT(L) HAS UNITS OF M/SEC
  !  DXYP(L) HAS UNITS OF M2
  !  WQATML(L,KC,NW) HAS UNITS OF G/DAY

  ! WQATML is returned and used in wqske1.f90

  CV2=86400.0
  DO NW=1,NWQV
    DO L=2,LA
      WQATML(L,KC,NW)=WQATM(NW)*RAINT(L)*DXYP(L)*CV2
    ENDDO
  ENDDO
  ! Qian not using code for IF( ITNWQ == 0 .AND. DEBUG )
  
  RETURN
END

